#!/usr/bin/env python3
"""Build a generic stage dictionary from Jenkins graph and config XML metadata."""

from __future__ import annotations

import argparse
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path


def _tag_name(element: ET.Element) -> str:
    return element.tag.split("}", 1)[-1]


def _text(node: ET.Element | None, default: str = "") -> str:
    if node is None or node.text is None:
        return default
    return node.text.strip()


def _load_graph(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _collect_subtree(graph: dict, root_job: str) -> list[str]:
    jobs = graph.get("jobs", {})
    if root_job not in jobs:
        raise KeyError(f"Root job '{root_job}' not found in graph")

    seen: set[str] = set()
    stack = [root_job]
    ordered: list[str] = []
    while stack:
        cur = stack.pop()
        if cur in seen:
            continue
        seen.add(cur)
        ordered.append(cur)
        downstream = jobs.get(cur, {}).get("downstream_jobs", [])
        stack.extend(reversed(downstream))
    return ordered


def _load_stage_map(path: Path | None) -> dict[str, str]:
    if not path:
        return {}
    if not path.exists():
        raise FileNotFoundError(path)
    data = json.loads(path.read_text(encoding="utf-8"))
    return {str(k): str(v) for k, v in data.items()}


def _default_stage_for_level(level: int) -> str:
    if level <= 0:
        return "phase-0"
    return f"phase-{level}"


def _parse_job_config(xml_path: Path) -> dict:
    if not xml_path.exists():
        return {
            "jenkins_class": "unknown",
            "assigned_node": "",
            "parameters": [],
            "build_steps": [],
        }

    root = ET.parse(xml_path).getroot()
    params = []
    for p in root.findall("./properties/hudson.model.ParametersDefinitionProperty/parameterDefinitions/*"):
        params.append(
            {
                "type": _tag_name(p),
                "name": _text(p.find("name")),
                "default": _text(p.find("defaultValue")),
            }
        )

    build_steps = [_tag_name(el) for el in root.findall("./builders/*")]
    return {
        "jenkins_class": root.attrib.get("class", _tag_name(root)),
        "assigned_node": _text(root.find("assignedNode")),
        "parameters": params,
        "build_steps": build_steps,
    }


def build_stage_dict(
    graph_path: Path,
    config_xml_dir: Path,
    logs_dir: Path,
    root_job: str,
    stage_map: dict[str, str],
) -> dict:
    graph = _load_graph(graph_path)
    jobs = graph.get("jobs", {})
    subtree_jobs = _collect_subtree(graph, root_job)

    stage_dict_jobs: dict[str, dict] = {}
    stage_sequence: set[str] = set()

    for job_name in subtree_jobs:
        meta = jobs.get(job_name, {})
        level = int(meta.get("level", -1))
        default_stage = stage_map.get(job_name) or _default_stage_for_level(level)
        stage_sequence.add(default_stage)

        xml_file = config_xml_dir / (re.sub(r"[\\/:*?\"<>|]", "_", job_name) + ".xml")
        parsed = _parse_job_config(xml_file)

        log_path = logs_dir / (re.sub(r"[\\/:*?\"<>|]", "_", job_name) + ".log")

        stage_dict_jobs[job_name] = {
            "job_name": job_name,
            "level": level,
            "jenkins_class": meta.get("class", parsed["jenkins_class"]),
            "assigned_node": parsed["assigned_node"],
            "parameters": parsed["parameters"],
            "build_steps": parsed["build_steps"],
            "upstream_jobs": meta.get("upstream_jobs", []),
            "downstream_jobs": meta.get("downstream_jobs", []),
            "has_build_log": log_path.exists(),
            "xml_path": str(xml_file),
            "log_path": str(log_path),
            "default_stage": default_stage,
            "allowed_stages": [default_stage],
            "allowed_stage_sequence": sorted(stage_sequence),
            "job_file_mode": "single-job",
        }

    ordered_stages = sorted(stage_sequence, key=lambda s: (int(s.split("-")[-1]) if s.split("-")[-1].isdigit() else 9999, s))

    return {
        "root_job": root_job,
        "stage_sequence": ordered_stages,
        "jobs": stage_dict_jobs,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build stage dictionary from Jenkins graph and XML evidence")
    parser.add_argument("--graph", default="fetch_xml/jenkins_graph_xml.json", help="Path to jenkins graph JSON (generated by fetch_jenkins_configs.py)")
    parser.add_argument("--config-xml-dir", default="fetch_xml/config_xml", help="Directory with Jenkins config XML files")
    parser.add_argument("--logs-dir", default="fetch_xml/build_logs", help="Directory with Jenkins build logs")
    parser.add_argument("--root", required=True, help="Root job name to build subtree stage dict")
    parser.add_argument("--stage-map", help="Optional JSON mapping: job name -> stage")
    parser.add_argument("--output", default="plugin_artifacts/stage_dict.json", help="Output JSON path")
    args = parser.parse_args()

    stage_map = _load_stage_map(Path(args.stage_map)) if args.stage_map else {}

    stage_dict = build_stage_dict(
        graph_path=Path(args.graph),
        config_xml_dir=Path(args.config_xml_dir),
        logs_dir=Path(args.logs_dir),
        root_job=args.root,
        stage_map=stage_map,
    )

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(stage_dict, indent=2), encoding="utf-8")
    print(f"Wrote stage dictionary for {len(stage_dict['jobs'])} jobs -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
