"""
GitLab CI/CD Pipeline Decoupler
Generates skip-ahead pipeline modifications using phase-based conditional includes.
"""

import yaml
import os
import copy
from typing import Dict, List, Set, Any, Optional
from collections import defaultdict

from .analyzer import AnalysisResult, PhaseInfo, JobInfo


class PipelineDecoupler:
    """Generates modified pipeline YAML with skip-ahead support."""

    def __init__(self, analysis: AnalysisResult):
        self.analysis = analysis
        self.pipeline_dir = analysis.pipeline_dir

    def generate(self, output_dir: str) -> Dict[str, str]:
        """Generate all modified pipeline files.

        Returns dict of { relative_path: file_content }.
        """
        files = {}

        # 1. Generate the modified parent .gitlab-ci.yml
        parent_content = self._generate_parent_ci()
        files[self.analysis.ci_file] = parent_content

        # 2. Generate bootstrap jobs for phases > 1
        for phase in self.analysis.phases[1:]:
            bootstrap_path, bootstrap_content = self._generate_bootstrap(phase)
            if bootstrap_content:
                files[bootstrap_path] = bootstrap_content

        # 3. Generate a summary/README with instructions
        files["DECOUPLING_PLAN.md"] = self._generate_plan_doc()

        return files

    # ── Parent .gitlab-ci.yml Generator ──────────────────────────────────

    def _generate_parent_ci(self) -> str:
        """Generate the modified .gitlab-ci.yml with conditional includes and RUN_FROM_PHASE."""
        # Read the original file
        original_path = os.path.join(self.pipeline_dir, self.analysis.ci_file)
        with open(original_path, 'r', encoding='utf-8') as f:
            original_data = yaml.safe_load(f)

        if not isinstance(original_data, dict):
            return ""

        lines = []
        lines.append("# ======================================================================")
        lines.append("# DECOUPLED PIPELINE — Generated by Pipeline Decoupler")
        lines.append("# Supports RUN_FROM_PHASE variable for skip-ahead execution.")
        lines.append("# ======================================================================")
        lines.append("")

        # Stages — keep original stages list + add bootstrap stages
        lines.append("stages:")
        # We need bootstrap stages inserted before each phase > 1
        all_stages = list(self.analysis.stages)
        bootstrap_stages = {}
        for phase in self.analysis.phases[1:]:
            bs_stage = f"bootstrap-phase-{phase.id}"
            # Insert bootstrap stage just before the first stage of this phase
            if phase.stages_covered:
                first_stage = phase.stages_covered[0]
                if first_stage in all_stages:
                    idx = all_stages.index(first_stage)
                    all_stages.insert(idx, bs_stage)
                    bootstrap_stages[phase.id] = bs_stage

        for stage in all_stages:
            lines.append(f"  - {stage}")
        lines.append("")

        # Variables — keep original + add RUN_FROM_PHASE
        lines.append("# Pipeline-level variables")
        lines.append("variables:")

        # Preserve original variables
        if 'variables' in original_data:
            for var_name, var_val in original_data['variables'].items():
                if isinstance(var_val, dict):
                    lines.append(f"  {var_name}:")
                    for k, v in var_val.items():
                        lines.append(f'    {k}: "{v}"')
                else:
                    lines.append(f'  {var_name}: "{var_val}"')

        # Add RUN_FROM_PHASE
        lines.append("  RUN_FROM_PHASE:")
        lines.append('    value: "1"')
        phase_options = ", ".join([f"{p.id}={p.name}" for p in self.analysis.phases])
        lines.append(f'    description: "Start from phase: {phase_options}"')
        lines.append("")

        # Includes — grouped by phase with rules
        lines.append("# Conditional includes — only loads job files for phases that will run")
        lines.append("include:")

        # Map include files to phases
        include_phase_map = self._map_includes_to_phases()

        for phase in self.analysis.phases:
            lines.append(f"  # --- Phase {phase.id}: {phase.name} ---")

            # Build the rules condition: include if RUN_FROM_PHASE <= this phase id
            phase_conditions = " || ".join(
                [f'$RUN_FROM_PHASE == "{i}"' for i in range(1, phase.id + 1)]
            )

            # Get include files for this phase
            phase_includes = include_phase_map.get(phase.id, [])

            # Add bootstrap file for phases > 1
            if phase.id > 1:
                bs_file = f"ci/phases/bootstrap-phase-{phase.id}.yml"
                lines.append(f"  - local: {bs_file}")
                lines.append(f"    rules:")
                # Bootstrap only runs when we're SKIPPING to this phase (not in full run)
                skip_conditions = " || ".join(
                    [f'$RUN_FROM_PHASE == "{i}"' for i in range(phase.id, len(self.analysis.phases) + 1)]
                )
                lines.append(f'      - if: \'{skip_conditions}\'')
                lines.append(f"        when: always")

            for inc_file in phase_includes:
                # GitLab requires forward slashes in include paths
                inc_file_normalized = inc_file.replace('\\', '/')
                lines.append(f"  - local: {inc_file_normalized}")
                if phase.id > 1:
                    lines.append(f"    rules:")
                    lines.append(f'      - if: \'{phase_conditions}\'')
                    lines.append(f"        when: always")

        lines.append("")
        return "\n".join(lines) + "\n"

    # ── Bootstrap Job Generator ──────────────────────────────────────────

    def _generate_bootstrap(self, phase: PhaseInfo) -> tuple:
        """Generate a bootstrap job file for a phase.

        The bootstrap job runs when prior phases are skipped, re-reading
        workspace state to provide dotenv variables that prior phases would
        have produced.
        """
        if not phase.dotenv_sources:
            # No dotenv deps from prior phases — still generate a minimal bootstrap
            pass

        bs_path = f"ci/phases/bootstrap-phase-{phase.id}.yml"
        bs_stage = f"bootstrap-phase-{phase.id}"

        lines = []
        lines.append(f"# Bootstrap job for Phase {phase.id}: {phase.name}")
        lines.append(f"# Runs when RUN_FROM_PHASE >= {phase.id}, re-reading workspace state")
        lines.append(f"# to provide variables that prior-phase dotenv producers would have set.")
        lines.append(f"#")
        lines.append(f"# Dotenv sources from prior phases: {', '.join(phase.dotenv_sources) or 'none'}")
        lines.append("")

        # Identify what dotenv files the prior phases produce
        dotenv_files = []
        for src_job_name in phase.dotenv_sources:
            src_job = self.analysis.jobs.get(src_job_name)
            if src_job and src_job.dotenv_file:
                dotenv_files.append((src_job_name, src_job.dotenv_file))

        job_name = f"bootstrap-phase-{phase.id}"
        lines.append(f"{job_name}:")
        lines.append(f"  stage: {bs_stage}")
        lines.append(f"  tags:")
        lines.append(f"    - windows")
        lines.append(f"  timeout: 5 minutes")
        lines.append(f"  variables:")
        lines.append(f"    GIT_STRATEGY: none")
        lines.append(f"  rules:")

        # Only run when skipping to this phase or later
        skip_conditions = " || ".join(
            [f'$RUN_FROM_PHASE == "{i}"' for i in range(phase.id, len(self.analysis.phases) + 1)]
        )
        lines.append(f'    - if: \'{skip_conditions}\'')
        lines.append(f"      when: always")
        lines.append(f"    - when: never")

        lines.append(f"  script:")
        lines.append(f"    - |")
        lines.append(f"      Write-Host '=== Bootstrap for Phase {phase.id}: {phase.name} ==='")
        lines.append(f"      Write-Host 'Re-reading workspace state from prior phase artifacts...'")

        if dotenv_files:
            lines.append(f"    - |")
            lines.append(f"      # Re-read dotenv files from workspace (they persist on disk from prior runs)")
            for src_name, dotenv_file in dotenv_files:
                lines.append(f"      # From {src_name}: {dotenv_file}")
                lines.append(f"      $envFile = '{dotenv_file}'")
                lines.append(f"      if (Test-Path $envFile) {{")
                lines.append(f"        Write-Host \"Reading $envFile\"")
                lines.append(f"        Get-Content $envFile | ForEach-Object {{")
                lines.append(f"          if ($_ -match '^([^=]+)=(.*)$') {{")
                lines.append(f"            $_ | Add-Content bootstrap_phase{phase.id}.env")
                lines.append(f"            Write-Host \"  $($Matches[1])=$($Matches[2])\"")
                lines.append(f"          }}")
                lines.append(f"        }}")
                lines.append(f"      }} else {{")
                lines.append(f"        Write-Warning \"Dotenv file not found: $envFile — variables may be missing\"")
                lines.append(f"      }}")
        else:
            lines.append(f"    - |")
            lines.append(f"      # No dotenv dependencies from prior phases")
            lines.append(f"      Write-Host 'No dotenv files to re-read for this phase.'")
            lines.append(f"      'BOOTSTRAP_PHASE={phase.id}' | Set-Content bootstrap_phase{phase.id}.env")

        lines.append(f"    - |")
        lines.append(f"      Write-Host 'Bootstrap complete.'")

        lines.append(f"  artifacts:")
        lines.append(f"    reports:")
        lines.append(f"      dotenv: bootstrap_phase{phase.id}.env")
        lines.append(f"    expire_in: 5 days")
        lines.append("")

        return bs_path, "\n".join(lines) + "\n"

    # ── Cross-Phase Needs Modification ───────────────────────────────────

    def generate_needs_modifications(self) -> Dict[str, List[Dict[str, Any]]]:
        """Identify needs: entries that should get optional: true for skip-ahead.

        Returns: { source_file: [ {job: ..., need_job: ..., add_optional: true} ] }
        """
        modifications = defaultdict(list)

        for phase in self.analysis.phases[1:]:
            for job_name, prior_deps in phase.cross_phase_needs.items():
                job = self.analysis.jobs.get(job_name)
                if not job:
                    continue
                for dep in prior_deps:
                    modifications[job.source_file].append({
                        'job': job_name,
                        'need_job': dep,
                        'action': 'add_optional_true',
                        'reason': f'{dep} is in Phase {self._get_phase_for_job(dep)}, may be skipped',
                    })

                # Also add bootstrap job to needs
                bs_job = f"bootstrap-phase-{phase.id}"
                modifications[job.source_file].append({
                    'job': job_name,
                    'need_job': bs_job,
                    'action': 'add_bootstrap_need',
                    'reason': f'Bootstrap provides variables when Phase {phase.id - 1} is skipped',
                })

        return dict(modifications)

    # ── Include-to-Phase Mapping ─────────────────────────────────────────

    def _map_includes_to_phases(self) -> Dict[int, List[str]]:
        """Map each include file to the phase it belongs to."""
        # Build job -> source_file mapping
        file_to_jobs = defaultdict(set)
        for name, job in self.analysis.jobs.items():
            if job.source_file:
                file_to_jobs[job.source_file].add(name)

        # Build job -> phase mapping
        job_to_phase = {}
        for phase in self.analysis.phases:
            for j in phase.jobs:
                job_to_phase[j] = phase.id

        # Map include files to phases
        include_to_phase = {}
        for inc_file in self.analysis.include_files:
            jobs_in_file = file_to_jobs.get(inc_file, set())
            if jobs_in_file:
                # All jobs in this file should be in the same phase (usually)
                phases = {job_to_phase.get(j, 1) for j in jobs_in_file}
                # Use the highest phase (most conservative — include it earlier)
                include_to_phase[inc_file] = min(phases)
            else:
                # Template-only files — include in phase 1
                include_to_phase[inc_file] = 1

        # Group by phase
        result = defaultdict(list)
        for inc_file, phase_id in include_to_phase.items():
            result[phase_id].append(inc_file)

        return dict(result)

    def _get_phase_for_job(self, job_name: str) -> int:
        """Return the phase ID a job belongs to."""
        for phase in self.analysis.phases:
            if job_name in phase.jobs:
                return phase.id
        return 0

    # ── Plan Documentation ───────────────────────────────────────────────

    def _generate_plan_doc(self) -> str:
        """Generate a markdown document explaining the decoupling."""
        lines = []
        lines.append("# Pipeline Decoupling Plan")
        lines.append("")
        lines.append("## Overview")
        lines.append("")
        lines.append(f"This pipeline has been split into **{len(self.analysis.phases)} phases** ")
        lines.append(f"with a `RUN_FROM_PHASE` variable that allows skipping completed phases.")
        lines.append("")
        lines.append("When a job fails late in the pipeline, fix the code, push, and set ")
        lines.append("`RUN_FROM_PHASE` to the phase containing the failed job. All prior phases ")
        lines.append("are skipped — their outputs already exist on the runner's persistent workspace.")
        lines.append("")

        lines.append("## Phases")
        lines.append("")
        for phase in self.analysis.phases:
            lines.append(f"### Phase {phase.id}: {phase.name}")
            lines.append("")
            lines.append(f"- **Stages**: {', '.join(phase.stages_covered)}")
            lines.append(f"- **Jobs** ({len(phase.jobs)}):")
            for j in phase.jobs:
                job = self.analysis.jobs.get(j)
                stage_str = f"[{job.stage}]" if job else ""
                lines.append(f"  - `{j}` {stage_str}")
            lines.append(f"- **Exit checkpoint**: `{phase.exit_job}`")
            if phase.cross_phase_needs:
                lines.append(f"- **Depends on prior phases**:")
                for j, deps in phase.cross_phase_needs.items():
                    lines.append(f"  - `{j}` needs: {', '.join(f'`{d}`' for d in deps)}")
            if phase.dotenv_sources:
                lines.append(f"- **Dotenv from prior phases**: {', '.join(f'`{d}`' for d in phase.dotenv_sources)}")
            lines.append("")

        lines.append("## Usage")
        lines.append("")
        lines.append("### Full pipeline run (default)")
        lines.append("```")
        lines.append("RUN_FROM_PHASE = 1")
        lines.append("```")
        lines.append("")
        for i, phase in enumerate(self.analysis.phases):
            if i == 0:
                continue
            lines.append(f"### Skip to Phase {phase.id}: {phase.name}")
            lines.append("```")
            lines.append(f"RUN_FROM_PHASE = {phase.id}")
            lines.append("```")
            skipped = [f"Phase {p.id} ({p.name})" for p in self.analysis.phases[:i]]
            lines.append(f"Skips: {', '.join(skipped)}")
            lines.append("")

        lines.append("## How It Works")
        lines.append("")
        lines.append("1. `include: rules:` conditionally loads job definition files per phase")
        lines.append("2. When phases are skipped, a **bootstrap job** runs instead, re-reading ")
        lines.append("   environment variables from the workspace (dotenv files from prior runs)")
        lines.append("3. Cross-phase `needs:` use `optional: true` so they don't fail when ")
        lines.append("   the upstream job doesn't exist (was in a skipped phase)")
        lines.append("4. The bootstrap job's dotenv artifact provides the same variables")
        lines.append("")

        lines.append("## Pre-requisites for Skip-Ahead")
        lines.append("")
        lines.append("- Prior phases must have completed successfully at least once")
        lines.append("- The runner workspace is persistent (not ephemeral)")
        lines.append("- Dotenv artifact files from prior runs still exist on disk")
        lines.append("")

        lines.append("## Needs Modifications Required")
        lines.append("")
        mods = self.generate_needs_modifications()
        if mods:
            for source_file, mod_list in mods.items():
                lines.append(f"### `{source_file}`")
                for mod in mod_list:
                    if mod['action'] == 'add_optional_true':
                        lines.append(f"- `{mod['job']}`: add `optional: true` to need `{mod['need_job']}`")
                    elif mod['action'] == 'add_bootstrap_need':
                        lines.append(f"- `{mod['job']}`: add need `{mod['need_job']}` (optional, artifacts: true)")
                lines.append("")
        else:
            lines.append("No cross-phase needs modifications required.")
            lines.append("")

        return "\n".join(lines) + "\n"


def decouple_pipeline(analysis: AnalysisResult, output_dir: str) -> Dict[str, str]:
    """Convenience function to generate decoupled pipeline files."""
    decoupler = PipelineDecoupler(analysis)
    return decoupler.generate(output_dir)
